# Generated by Django 4.1.4 on 2023-01-05 06:16

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.CharField(max_length=100)),
                ('blog_image', versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Blog Image')),
                ('blogger_name', models.CharField(max_length=100)),
                ('blog_date', models.DateField()),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image')),
                ('place_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image')),
                ('service_name', models.CharField(max_length=100)),
                ('service_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image')),
                ('review', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
    ]
