# Generated by Django 4.1.4 on 2023-01-05 08:27

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_place_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('package_details', models.TextField()),
                ('image_1', versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image1')),
                ('image_2', versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image2')),
                ('image_3', versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image3')),
                ('image_4', versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image4')),
                ('image_5', versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image5')),
                ('image_6', versatileimagefield.fields.VersatileImageField(upload_to='image/testimagemodel/', verbose_name='Image6')),
                ('group_size', models.CharField(max_length=100)),
                ('number_of_days', models.IntegerField()),
                ('number_of_nights', models.IntegerField()),
                ('rate', models.CharField(max_length=100)),
                ('tour_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tourtype')),
            ],
        ),
    ]
