# Generated by Django 4.1.4 on 2023-01-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_tourtype_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='total_days',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
